import { useState } from "react";
import { ThemeProvider } from "styled-components";
import type { AppProps } from "next/app";
import Head from "next/head";

import { theme } from "../theme";
import { GlobalStyle } from "../styles";

type ThemeType = "light" | "dark";

function MyApp({ Component, pageProps }: AppProps) {
  const [activeTheme, setActiveTheme] = useState<ThemeType>("dark");
  const pagePropsWithTheme = { ...pageProps, setActiveTheme };

  return (
    <ThemeProvider theme={theme[activeTheme]}>
      <Head>
        <title>CAIOALCANTARA.DEV - SOFTWARE ENGINEER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pagePropsWithTheme} />
      <GlobalStyle />
    </ThemeProvider>
  );
}

export default MyApp;
