import { MediumService } from "../services";
import Head from "next/head";

import { Layout, CardSection } from "../components";

type HomeProps = {
  posts: any[];
};

const Home = ({ posts }: HomeProps) => {
  return (
    <Layout>
      <Head>
        <title>CAIOALCANTARA.DEV - SOFTWARE ENGINEER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CardSection title="Last posts" cards={posts} />
      {/* <CardSection title="Projects" cards={posts} /> */}
    </Layout>
  );
};

export async function getServerSideProps() {
  const { items } = await MediumService.getPosts("clucasalcantara");

  return {
    props: {
      posts: items,
    },
  };
}

export default Home;
